function getTestRequest(){
  return {
  "range": "league_schedule!A1:AY1001",
  "majorDimension": "ROWS",
  "values": [
    [
      "leagueType",
      "date",
      "matchNum",
      "time",
      "homeGame",
      "freeholdTeam",
      "opponent",
      "result",
      "division",
      "location",
      "year",
      "sex",
      "field",
      "fieldNum",
      "Month_Date"
    ],
    [
      "EDP",
      "Sunday, March 01, 2023",
      "1023",
      "10:30 AM",
      "HOME",
      "Phoenix (NJ)",
      "RCD Espanyol de Barcelona NJ RCD Español de Barcelona NJ 2004 Elite (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "JM1",
      "JM1",
      "Central",
      "",
      "OP6",
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "7339",
      "10:30 AM",
      "HOME",
      "Elite Phantoms (NJ)",
      "SJ Futbol Club SJFC Venom",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "JM2",
      "JM2",
      "Central",
      "",
      "JM2",
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "8461",
      "10:30 AM",
      "AWAY",
      "Elite Fusion",
      "Real Jersey FC Real Jersey FC 2011 EDP Premier",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "JM3",
      "JM3",
      "Central",
      "",
      "",
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "6553",
      "",
      "AWAY",
      "Elite Storm (NJ)",
      "Deptford Premier FC Deptford Premier FC '06 Girls (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "9948",
      "10:30 AM",
      "HOME",
      "Elite Warriors",
      "Staten Island Soccer Club SISC Arsenal 2009 Boys",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central",
      "",
      "JM3",
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "8953",
      "",
      "HOME",
      "Union (NJ)",
      "Valencia Soccer Academy Valencia 09 Black",
      "-",
      "15B Central Atlantic Premier V Blue",
      "",
      "15B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "8047",
      "",
      "HOME",
      "Elite Galaxy",
      "Upper 90 Soccer Academy NJ UPPER 90 RED BULLS 2010B",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "1109",
      "",
      "HOME",
      "Reign",
      "Princeton SA PSA Princeton '11",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "2",
      "",
      "HOME",
      "Elite Freedom",
      "Valencia Soccer Academy Valencia 12G Black",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "360",
      "",
      "HOME",
      "Rockets (NJ)",
      "Howell United SC Howell United SC 2012G Stars (NJ)",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "1775",
      "",
      "AWAY",
      "Elite Thunder",
      "Cedar Stars Academy North Bergen 2010 Girls EDP",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, March 26, 2023",
      "2128",
      "",
      "AWAY",
      "Elite Falcons",
      "TSF Academy 2012 Boys White",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Saturday, April 1, 2023",
      "1841",
      "12:00 PM",
      "AWAY",
      "Elite Breakers",
      "Central Jersey Futbol Alliance CJFA Wave",
      "-",
      "13G Central Atlantic Premier lV Red",
      "Hazlet United Soccer Complex - Field #4",
      "13G",
      "Central",
      "Hazlet United Soccer Complex",
      "Field #4"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "8",
      "",
      "AWAY",
      "Elite Freedom",
      "SJEB FC 12G Pre-GA",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "1028",
      "",
      "AWAY",
      "Phoenix (NJ)",
      "North Jersey FC North Jersey FC 2004B  (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "",
      "19B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "2131",
      "",
      "HOME",
      "Elite Falcons",
      "Cheshire Soccer Academy Cheshire Soccer Academy 2012 Boys NL",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "1113",
      "",
      "AWAY",
      "Reign",
      "Stateline SC Stateline SC-2011G Bears",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "7341",
      "",
      "AWAY",
      "Elite Phantoms (NJ)",
      "Marlton Soccer Club Marlton SC Chiefs Orange 2007 (NJ)",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "",
      "16B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "8053",
      "",
      "AWAY",
      "Elite Galaxy",
      "Torpedoes SC Torpedoes BU12 Red",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "8955",
      "",
      "AWAY",
      "Union (NJ)",
      "Mercer United FC Mercer United FC Hurricanes Black",
      "-",
      "15B Central Atlantic Premier V Blue",
      "",
      "15B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "9950",
      "",
      "AWAY",
      "Elite Warriors",
      "Howell United SC Howell United SC Bulldogs (NJ)",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "4931",
      "",
      "AWAY",
      "Elite Force (NJ)",
      "Jersey Knights SC Jersey Knights SC Valkyries 2008",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "",
      "15G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "6556",
      "",
      "HOME",
      "Elite Storm (NJ)",
      "Cohansey SC Cohansey Premier 2006G (EDP) (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "362",
      "",
      "AWAY",
      "Rockets (NJ)",
      "PDA South PDA South 2012 Thorns",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 2, 2023",
      "1850",
      "10:30 AM",
      "HOME",
      "Elite Breakers",
      "Middletown SC Fire Red",
      "-",
      "13G Central Atlantic Premier lV Red",
      "Jackson Mills  - JM1",
      "13G",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "1116",
      "",
      "HOME",
      "Reign",
      "WSA Union County FC Lille",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "1854",
      "",
      "HOME",
      "Elite Breakers",
      "Monmouth United Soccer MUSC 2010 Girls Premier",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "2136",
      "",
      "AWAY",
      "Elite Falcons",
      "Lduq-usa Pro LDUQ-USA PRO FC U11",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "1784",
      "",
      "AWAY",
      "Elite Thunder",
      "Cedar Stars Academy North Bergen 2011 Girls EDP",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "367",
      "",
      "HOME",
      "Rockets (NJ)",
      "Medford SC Medford SC United 2012",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "7348",
      "",
      "HOME",
      "Elite Phantoms (NJ)",
      "Mount Laurel United (MLU) Chargers 2007 (NJ)",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "",
      "16B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "12",
      "",
      "HOME",
      "Elite Freedom",
      "Real Jersey FC Real Jersey FC 2012 Pre-GA",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "6560",
      "",
      "AWAY",
      "Elite Storm (NJ)",
      "Jersey Shore Boca Jr FC Barrera (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "8962",
      "10:30 AM",
      "HOME",
      "Union (NJ)",
      "Middletown SC Revolution Red (NJ)",
      "-",
      "15B Central Atlantic Premier V Blue",
      "Jackson Mills  - JM1",
      "15B",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "8467",
      "",
      "HOME",
      "Elite Fusion",
      "Jackson SC Tecnica Elite Soccer '11 Boys - Jackson",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "8054",
      "",
      "HOME",
      "Elite Galaxy",
      "World Class FC SCP World Class FC SCP - 2010/11 Boys",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 16, 2023",
      "1030",
      "",
      "HOME",
      "Phoenix (NJ)",
      "Cruzeiro EC USA/USC Cruzeiro U19 (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "",
      "19B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "1859",
      "",
      "AWAY",
      "Elite Breakers",
      "Match Fit Academy FC Girls Mercer 2010",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "4932",
      "3:15 PM",
      "HOME",
      "Elite Force (NJ)",
      "US Parma Gold 08 (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "Jackson Mills  - JM1",
      "15G",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "7349",
      "",
      "HOME",
      "Elite Phantoms (NJ)",
      "Cherry Hill FC 2007 Premier Diablos (NJ)",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "",
      "16B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "17",
      "",
      "AWAY",
      "Elite Freedom",
      "PDA 2013G Stars Blue",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "2142",
      "",
      "HOME",
      "Elite Falcons",
      "Stateline SC Stateline SC-2012B Eagles",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "371",
      "",
      "AWAY",
      "Rockets (NJ)",
      "Deptford Premier FC Deptford Premier FC '12 Girls",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "1122",
      "",
      "AWAY",
      "Reign",
      "Ocean Township United SA OTUSA 2011G Hammers Red (NJ)",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "6565",
      "",
      "HOME",
      "Elite Storm (NJ)",
      "Franklin Elite Phoenix 2006 (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "8472",
      "",
      "AWAY",
      "Elite Fusion",
      "Princeton SA PSA North '11 Orange Boys",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "1033",
      "",
      "AWAY",
      "Phoenix (NJ)",
      "FC Pocono FC Pocono 2004 Boys (PAE)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "",
      "19B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "8963",
      "",
      "HOME",
      "Union (NJ)",
      "South Brunswick South Brunswick Hi-Tempo Academy (NJ)",
      "-",
      "15B Central Atlantic Premier V Blue",
      "",
      "15B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 23, 2023",
      "9959",
      "",
      "AWAY",
      "Elite Warriors",
      "Middletown SC Force Red",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "8062",
      "",
      "AWAY",
      "Elite Galaxy",
      "West New York SC WNY Tigers U13",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "1793",
      "",
      "AWAY",
      "Elite Thunder",
      "RYSA Wildcats Youth Soccer RYSA G2010",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "2149",
      "",
      "AWAY",
      "Elite Falcons",
      "Titanes SC Titos (NJ)",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "1123",
      "",
      "HOME",
      "Reign",
      "Cedar Stars Academy (Staten Island) G2011 Green",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "7355",
      "",
      "AWAY",
      "Elite Phantoms (NJ)",
      "Brick Township SA United (NJ)",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "",
      "16B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "22",
      "",
      "HOME",
      "Elite Freedom",
      "PDA 2012G Express 1",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "1037",
      "",
      "HOME",
      "Phoenix (NJ)",
      "Steel United NJ Steel United NJ 2004B Elite (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "",
      "19B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "8474",
      "",
      "HOME",
      "Elite Fusion",
      "PDA Hibernian Keller 2011",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "8969",
      "",
      "AWAY",
      "Union (NJ)",
      "WSA Union County FC Villa (NJ)",
      "-",
      "15B Central Atlantic Premier V Blue",
      "",
      "15B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "9966",
      "",
      "AWAY",
      "Elite Warriors",
      "Jersey Shore Boca Jr FC Rooney",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "4940",
      "2:20 PM",
      "AWAY",
      "Elite Force (NJ)",
      "World Class FC SCP 2008 EDP (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "Pope John HS - Blue Turf Upper",
      "15G",
      "Central",
      "Pope John HS",
      "Blue Turf Upper"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "6567",
      "",
      "AWAY",
      "Elite Storm (NJ)",
      "TBAA TBAA Premier 2006 Thunder (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "1864",
      "",
      "HOME",
      "Elite Breakers",
      "Upper Freehold/Allentown SA UFA Freedom",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, April 30, 2023",
      "374",
      "",
      "HOME",
      "Rockets (NJ)",
      "Cape Express Wave 2012 (NJ)",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Thursday, May 4, 2023",
      "1796",
      "7:00 PM",
      "HOME",
      "Elite Thunder",
      "NJ Crush FC 2010 National",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "Opatut Park - OP5",
      "13G",
      "Central",
      "Opatut Park",
      "OP5"
    ],
    [
      "EDP",
      "Saturday, May 6, 2023",
      "9996",
      "",
      "HOME",
      "Elite Warriors",
      "Manalapan SC Manalapan SC United 09b (NJ)",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Saturday, May 6, 2023",
      "2176",
      "",
      "AWAY",
      "Elite Falcons",
      "FC Berna Legacy Legacy 2012 Boys Black",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Saturday, May 6, 2023",
      "8972",
      "10:15 AM",
      "HOME",
      "Union (NJ)",
      "Roselle Park Soccer Club Paragon",
      "-",
      "15B Central Atlantic Premier V Blue",
      "Opatut Park - OP5",
      "15B",
      "Central",
      "Opatut Park",
      "OP5"
    ],
    [
      "EDP",
      "Saturday, May 6, 2023",
      "8477",
      "10:35 AM",
      "AWAY",
      "Elite Fusion",
      "Lacey SC Cedar Stars Academy Lacey 2011B",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "Gille Park - Gille 2 11v11",
      "13B",
      "Central",
      "Gille Park",
      "Gille 2 11v11"
    ],
    [
      "EDP",
      "Sunday, May 7, 2023",
      "380",
      "",
      "AWAY",
      "Rockets (NJ)",
      "Old Bridge Girls Soccer Old Bridge Girls Soccer Storm White (NJ)",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 7, 2023",
      "1868",
      "",
      "AWAY",
      "Elite Breakers",
      "Old Bridge Girls Soccer Old Bridge Girls Soccer Elite",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "26",
      "",
      "AWAY",
      "Elite Freedom",
      "Match Fit Academy FC Girls Mercer 2012 Blue",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "2153",
      "",
      "HOME",
      "Elite Falcons",
      "SB4U Academy SB4U VENLO 2012",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "9969",
      "",
      "HOME",
      "Elite Warriors",
      "Twin County Soccer Association Twin County SA Inferno 2009 EDP",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "8069",
      "",
      "HOME",
      "Elite Galaxy",
      "Jersey Stars Soccer Club Jersey Stars River",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "1038",
      "1:00 PM",
      "AWAY",
      "Phoenix (NJ)",
      "Clifton Stallions Soccer Club Clifton Stallions - Sport Boys (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "Athenia Steel Park - Turf 1",
      "19B",
      "Central",
      "Athenia Steel Park",
      "Turf 1"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "6574",
      "",
      "AWAY",
      "Elite Storm (NJ)",
      "SJEB FC 06G NL (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "1789",
      "9:00 AM",
      "HOME",
      "Elite Thunder",
      "Morris Elite SC G10 Pre-USL",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "Jackson Mills  - JM1",
      "13G",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "4947",
      "3:00 PM",
      "HOME",
      "Elite Force (NJ)",
      "Pasco Soccer Club PASCO BLUES (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "Jackson Mills  - JM1",
      "15G",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, May 07, 2023",
      "7358",
      "",
      "HOME",
      "Elite Phantoms (NJ)",
      "Liverpool FC Academy NJ Liverpool FCNJ 2007B Red Burlington (NJ)",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "",
      "16B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "8481",
      "",
      "HOME",
      "Elite Fusion",
      "Princeton SA PSA Princeton '11",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "6575",
      "",
      "HOME",
      "Elite Storm (NJ)",
      "Ocean Township United SA OTUSA 2006G Fury Red (NJ)",
      "-",
      "17G Central Atlantic Premier III Blue",
      "",
      "17G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "2157",
      "",
      "AWAY",
      "Elite Falcons",
      "Wayne Soccer Club 2012B Green",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "1782",
      "10:30 AM",
      "HOME",
      "Elite Thunder",
      "STA Mount Olive Soccer Club STA Mt Olive SC STA MOSC 2010 USYS Girls",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "Jackson Mills  - JM1",
      "13G",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "8071",
      "",
      "AWAY",
      "Elite Galaxy",
      "Silver Lake Soccer Academy Thunder",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "35",
      "",
      "HOME",
      "Elite Freedom",
      "Wall Soccer Club Wall Elite Porto",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "8976",
      "",
      "AWAY",
      "Union (NJ)",
      "North Plainfield Soccer Elite NPSE Giants",
      "-",
      "15B Central Atlantic Premier V Blue",
      "",
      "15B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "1131",
      "",
      "AWAY",
      "Reign",
      "RUSA FC RUSA G2011 GOLD",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "7362",
      "",
      "AWAY",
      "Elite Phantoms (NJ)",
      "Cherry Hill SC Cherry Hill SC Fury 2007 (NJ)",
      "-",
      "16B Central Atlantic Premier IV Blue",
      "",
      "16B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "9974",
      "",
      "AWAY",
      "Elite Warriors",
      "Liverpool FC Academy NJ LFCNJ 2009 Boys Red Burlington",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "1874",
      "",
      "HOME",
      "Elite Breakers",
      "Marlton Soccer Club Marlton SC Tigers 2010",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "1802",
      "",
      "AWAY",
      "Elite Thunder",
      "Ironbound SC 2010 - THUNDER",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "4949",
      "",
      "AWAY",
      "Elite Force (NJ)",
      "Florham Park Soccer Club Panther Academy (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "",
      "15G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 14, 2023",
      "381",
      "",
      "HOME",
      "Rockets (NJ)",
      "Liverpool FC Academy NJ Liverpool FC NJ 2012 Girls South Red (NJ)",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Friday, May 19, 2023",
      "1803",
      "7:00 PM",
      "HOME",
      "Elite Thunder",
      "Match Fit Academy FC MFA Mercer 2011G",
      "-",
      "13G Central Atlantic Premier IV Blue",
      "Opatut Park - OP5",
      "13G",
      "Central",
      "Opatut Park",
      "OP5"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "8076",
      "",
      "HOME",
      "Elite Galaxy",
      "BSM Elite BSM Elite 2010 Cosmos",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "1046",
      "",
      "HOME",
      "Phoenix (NJ)",
      "North Jersey FC North Jersey FC 2004B  (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "",
      "19B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "9980",
      "",
      "HOME",
      "Elite Warriors",
      "Jersey Knights SC Jersey Knights SC Black Knights 2009",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "36",
      "",
      "HOME",
      "Elite Freedom",
      "The Football Academy NJ The FA 2012 Girls Black",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "4954",
      "3:00 PM",
      "HOME",
      "Elite Force (NJ)",
      "New Jersey Rush New Jersey Rush 08 Girls Grey (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "Jackson Mills  - JM1",
      "15G",
      "Central",
      "Jackson Mills",
      "JM1"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "2164",
      "",
      "HOME",
      "Elite Falcons",
      "SFL Club 2012 Boys Black",
      "-",
      "11B Central Atlantic Premier IV",
      "",
      "11B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "1138",
      "",
      "HOME",
      "Reign",
      "Marlboro Soccer Association 2011 Sparks Blue",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, May 21, 2023",
      "1877",
      "",
      "AWAY",
      "Elite Breakers",
      "Jersey South FC Jersey South FC Pride",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Saturday, June 3, 2023",
      "4925",
      "3:00 PM",
      "HOME",
      "Elite Force (NJ)",
      "Hunterdon FC NJ14 2008 Nemesis (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "Opatut Park - OP5",
      "15G",
      "Central",
      "Opatut Park",
      "OP5"
    ],
    [
      "EDP",
      "Saturday, June 3, 2023",
      "8485",
      "9:00 AM",
      "AWAY",
      "Elite Fusion",
      "Jackson SC Tecnica Elite Soccer '11 Boys - Jackson",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "Jackson Justice Complex - Field 2 11v11",
      "13B",
      "Central",
      "Jackson Justice Complex",
      "Field 2 11v11"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "1140",
      "",
      "AWAY",
      "Reign",
      "Liverpool FC Academy NJ Liverpool FCNJ 2011G South",
      "-",
      "12G Central Atlantic Premier V Blue",
      "",
      "12G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "8080",
      "",
      "AWAY",
      "Elite Galaxy",
      "NJ Stallions NJ Stallions 10 Barca EDP",
      "-",
      "13B Central Atlantic Premier Vl Blue",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "1884",
      "",
      "HOME",
      "Elite Breakers",
      "SJEB FC 10G NL",
      "-",
      "13G Central Atlantic Premier lV Red",
      "",
      "13G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "2166",
      "10:30 AM",
      "HOME",
      "Elite Falcons",
      "Toms River FC Zidane",
      "-",
      "11B Central Atlantic Premier IV",
      "Jackson Mills  - JM3",
      "11B",
      "Central",
      "Jackson Mills",
      "JM3"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "44",
      "",
      "AWAY",
      "Elite Freedom",
      "PDA South PDA South 2012 Angels",
      "-",
      "11G Central Atlantic Premier I Blue",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "9987",
      "",
      "AWAY",
      "Elite Warriors",
      "Penninsula SC Peninsula Juve Eagles (NJ)",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "389",
      "",
      "AWAY",
      "Rockets (NJ)",
      "Hibernian AA Hibernian AA Herricanes (NJ)",
      "-",
      "11G Central Atlantic Premier Vl",
      "",
      "11G",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 4, 2023",
      "1048",
      "",
      "AWAY",
      "Phoenix (NJ)",
      "Cruzeiro EC USA/USC Cruzeiro U19 (NJ)",
      "-",
      "19B Central Atlantic Premier III Blue",
      "",
      "19B",
      "Central"
    ],
    [
      "EDP",
      "Wednesday, June 7, 2023",
      "4958",
      "6:30 PM",
      "AWAY",
      "Elite Force (NJ)",
      "Holmdel FC Holmdel FC 2008 girls Eagles (NJ)",
      "-",
      "15G Central Atlantic Premier IV Blue",
      "Cross Farms - Field 3 (9v9)",
      "15G",
      "Central",
      "Cross Farms",
      "Field 3 (9v9)"
    ],
    [
      "EDP",
      "Sunday, June 11, 2023",
      "9991",
      "",
      "HOME",
      "Elite Warriors",
      "RUSA FC RUSA B2009 GOLD",
      "-",
      "14B Central Atlantic Premier Vl Blue",
      "",
      "14B",
      "Central"
    ],
    [
      "EDP",
      "Sunday, June 11, 2023",
      "8488",
      "",
      "HOME",
      "Elite Fusion",
      "Lacey SC Cedar Stars Academy Lacey 2011B",
      "-",
      "13B Central Atlantic Premier 12U 11v11",
      "",
      "13B",
      "Central"
    ],
    [
      "EDP Futures",
      "Friday, September 16, 2022",
      "3111",
      "7:15 PM",
      "HOME",
      "Blaze (NJ)",
      "Central Jersey Futbol Alliance CJFA Reign 2013 (NJ)",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "Capelli Sport Complex - Field 6",
      "GU10",
      "EDP",
      "Capelli Sport Complex",
      "Field 6"
    ],
    [
      "EDP Futures",
      "Saturday, September 24, 2022",
      "3109",
      "6:00 PM",
      "HOME",
      "Blaze (NJ)",
      "Staten Island Soccer Club SISC Lightning 2013 Girls (NYE)",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "Capelli Sport Complex - Field 6 - SS #1",
      "GU10",
      "EDP",
      "Capelli Sport Complex - Field 6",
      "SS #1"
    ],
    [
      "EDP Futures",
      "Saturday, October 1, 2022",
      "3110",
      "1:30 PM",
      "AWAY",
      "Blaze (NJ)",
      "Cedar Stars Academy - Monmouth 2013G White (NJ)",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "Capelli Sport Complex - Indoor Field",
      "GU10",
      "EDP",
      "Capelli Sport Complex",
      "Indoor Field"
    ],
    [
      "EDP Futures",
      "Wednesday, October 12, 2022",
      "3112",
      "6:00 PM",
      "AWAY",
      "Blaze (NJ)",
      "Central Jersey Futbol Alliance CJFA Reign 2013 (NJ)",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "Hazlet United Soccer Complex - Field #3A",
      "GU10",
      "EDP",
      "Hazlet United Soccer Complex",
      "Field #3A"
    ],
    [
      "EDP Futures",
      "Saturday, November 5, 2022",
      "3113",
      "1:30 PM",
      "AWAY",
      "Blaze (NJ)",
      "Lacey SC Cedar Stars Academy Lacey 2013G White (NJ)",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "Gille Park - Gille 1A 7v7",
      "GU10",
      "EDP",
      "Gille Park",
      "Gille 1A 7v7"
    ],
    [
      "EDP Futures",
      "Friday, November 11, 2022",
      "3115",
      "7:15 PM",
      "AWAY",
      "Blaze (NJ)",
      "FC Berna Legacy Legacy 2013 Girls Black",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "Mountain Park - Turf - Field 4",
      "GU10",
      "EDP",
      "Mountain Park - Turf",
      "Field 4"
    ],
    [
      "EDP Futures",
      "Monday, November 14, 2022",
      "3108",
      "6:00 PM",
      "HOME",
      "Blaze (NJ)",
      "FC Berna Legacy Legacy 2013 Girls Black",
      "-",
      "GU10 EDP Futures Central Red",
      "Opatut Park - OP6A",
      "GU10",
      "EDP",
      "Opatut Park",
      "OP6A"
    ],
    [
      "EDP Futures",
      "Sunday, November 20, 2022",
      "3114",
      "12:45 PM",
      "AWAY",
      "Blaze (NJ)",
      "Cedar Stars Academy (Staten Island) Cedar Stars Academy Staten Island G2013 Green",
      "Hidden",
      "GU10 EDP Futures Central Red",
      "College of Staten Island  - 7v7 A CSI Turf",
      "GU10",
      "EDP",
      "College of Staten Island",
      "7v7 A CSI Turf"
    ]
  ]
}
}